function HaService(){var g,e,B=0,b,p=0,i={},q=(new Date).getTime(),m=q,C=0,t=0,D=0,n=!1,u=!1,o=[],v=[],E=0,k=1,w=5,j=function(){var a={};if(window.HaSettingsObj)a.impressionId=$uid,a.dvObj=$dv,a.brid=window.HaSettingsObj.brid,a.numOfConsecutiveIterations=window.HaSettingsObj.numOfConsecutiveIterations,a.eventApi="/event.gif";else for(var b=[window.$dvbs,window.$dvbsr],f=0;f<b.length;f++){var c=b[f];if(c&&"object"===typeof c&&"function"===typeof c.getTagObjectByService){var h=c.getTagObjectByService("ha5");
if(h){var d=h.services.ha5;d&&d.params&&(a.impressionId=h.impressionId,a.dvObj=c,a.brid=d.params.brid,a.numOfConsecutiveIterations=d.params.numOfConsecutiveIterations,a.eventApi="/bsevent.gif")}}}return a}(),c=j.dvObj,d=j.impressionId,x=j.eventApi,r="swfReady_"+d,y="sampleCallback"+d;this.exec=function(){try{var a="object"===typeof $dvbs&&$dvbs===c||"object"===typeof $dvbsr&&$dvbsr===c?window:parent.window;g=a.innerWidth||a.document.documentElement.clientWidth||a.document.body.clientWidth}catch(F){g=
-1}try{var f="object"===typeof $dvbs&&$dvbs===c||"object"===typeof $dvbsr&&$dvbsr===c?window:parent.window;e=f.innerHeight||f.document.documentElement.clientHeight||f.document.body.clientHeight}catch(K){e=-1}k=j.brid;w=j.numOfConsecutiveIterations;d=j.impressionId;i.bucket_100=0;i.bucket_90_99=0;var h=window!=window.top,a=G(),f=H();h&&a&&f?(a=20*Math.random()+g/2-10,f=20*Math.random()+e/2-10,a==g/2&&(a=g/2+1),f==e/2&&(f=e/2+1),b=new I(a,f,d,c)):(h=c.tags[d].dv_protocol+"//"+(c.tags[d].ServerPublicDns||
c.tags[d].serverPublicDns)+x+"?impid="+d+"&dvp_isFrmNested="+(h?1:0),h=h+("&dvp_isFlshSupported="+(a?1:0))+("&dvp_frmSize="+g+"x"+e),h=h+("&dvp_isValidFrmSize="+(f?1:0))+("&dvp_isHiddenSupprted="+("undefined"!==typeof document.hidden?1:0)),c.domUtilities.addImage(h+"dvp_hdnVer=5",c.tags[d].tagElement.parentElement))};c[y]=function(a){t++;"throttle"==a?b.isHdn=1:"resume"==a&&(b.isHdn=0);z();"throttle"==a&&o.push("t");"resume"==a&&o.push("r");v.push((new Date).getTime()-q);20<o.length&&(o.shift(),v.shift())};
var z=function(){0==b.isHdn?(0!=m&&(p+=(new Date).getTime()-m),m=(new Date).getTime()):0==m};c[r]=function(){try{var a=c.tags[d].tagElement.parentElement.ownerDocument.getElementById("swfdetect_"+d);b?(b.swf=a,b.readyMs=(new Date).getTime()-q,setTimeout(A,100)):200>B++&&setTimeout(function(){c[r]()},50)}catch(F){}};var A=function(){0==t?3>=++D?setTimeout(A,250):(b.isHdn=0,s()):s()},s=function(){C++;z();if(3==k){if(0==b.isHdn&&1E3<=p){l(["hdn=0"]);return}}else{var a=!0;if(c.tags[d].getViewabilityData&&
"function"==typeof c.tags[d].getViewabilityData&&(J()?(1==b.isHdn?document.hidden?1==b.prevIsHdnAndPageHdn?b.consecutiveFraudHiddenIterationsAndPageHdn++:b.consecutiveFraudHiddenIterationsAndPageHdn=1:1==b.prevIsHdn?b.consecutiveFraudHiddenIterations++:b.consecutiveFraudHiddenIterations=1:0==b.isHdn&&(n?l(["dvp_wasHdn=1","hdn=0"]):l(["hdn=0"]),a=!1,b.hide()),b.prevIsHdn=b.isHdn,b.prevIsHdnAndPageHdn=1==b.isHdn&&1==document.hidden?1:0):(b.consecutiveFraudHiddenIterations=0,b.consecutiveFraudHiddenIterationsAndPageHdn=
0),b.consecutiveFraudHiddenIterations>=w&&!n&&(l(["hdn=1"]),n=!0),5<=b.consecutiveFraudHiddenIterationsAndPageHdn&&!u))l(["dvp_popU=1"]),u=n=!0;0==b.isHdn&&3<E++&&(a=!1,b.hide())}(a||3==k)&&setTimeout(function(){s()},1E3)},I=function(a,b,f,c){var d="swfdetect_"+f,g=3==k?"transparent":"window",e=document.createElement("div");this.readyMs=-1;this.wasHidden=this.consecutiveFraudHiddenIterationsAndPageHdn=this.consecutiveFraudHiddenIterations=0;this.swf=null;this.isHdn=3==k?0:-1;this.prevIsHdnAndPageHdn=
this.prevIsHdn=0;this.isVisible=!0;this.hide=function(){e.style.display="none"};e.id="swfDiv";e.style.width="1px";e.style.height="1px";e.style.position="absolute";e.style.left=a+"px";e.style.top=b+"px";a="object"===typeof $dvbs&&$dvbs===c?"$dvbs.":"object"===typeof $dvbsr&&$dvbsr===c?"$dvbsr.":"$dv.";d='<object id="'+d+'" data="'+c.tags[f].dv_protocol+'//cdn.doubleverify.com/dvdtc.swf"  type="application/x-shockwave-flash" bgcolor="#000000" width="1" height="1" allowScriptAccess="always" wmode="'+
g+'">';d+='<param name="data" value="'+c.tags[f].dv_protocol+'//cdn.doubleverify.com/dvdtc.swf" />';d+='<param name="flashvars" value="swfCountTiming=1000&swfReadyCallbackName='+a+r+"&swfSamplePixelStateCallbackName="+a+y+'" />';e.innerHTML=d+'<param name="quality" value="high"/><param name="bgcolor" value="#000000"/><param name="allowScriptAccess" value="always" />'+('<param name="wmode" value="'+g+'" />')+"</object>";c.tags[f].tagElement.ownerDocument.body.appendChild(e)},l=function(a){var b=c.tags[d],
b=b.dv_protocol+"//"+(b.ServerPublicDns||b.serverPublicDns)+x+"?impid="+d,f=[];f.push("dvp_hdnVer=5");if("undefined"!==typeof a)for(var e=0;e<a.length;e++)f.push(a[e]);b+="&"+f.join("&");c.domUtilities.addImage(b,c.tags[d].tagElement.parentElement)},G=function(){var a=0;try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.11"),!0}catch(b){}try{if(a=navigator.plugins["Shockwave Flash"].description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1].split(",")[0],11<=a)return!0}catch(c){}return!1},
J=function(){var a=!1;if(c.tags[d].getViewabilityData&&"function"==typeof c.tags[d].getViewabilityData)try{var b=c.tags[d].getViewabilityData().buckets;if(b.bucket_100>i.bucket_100||b.bucket_90_99>i.bucket_90_99)a=!0;i.bucket_100=b.bucket_100;i.bucket_90_99=b.bucket_90_99}catch(f){}return a},H=function(){var a=function(a,b,c){c*=b;return a<=b+c&&a>=b-c};return a(g,300,0.1)&&a(e,250,0.1)||a(g,300,0.1)&&a(e,600,0.1)||a(g,728,0.1)&&a(e,90,0.1)||a(g,160,0.1)&&a(e,600,0.1)}}try{(new HaService).exec()}catch(e$$10){};
